/**:
  ros__parameters:
    car_width: 0.27
    car_length: 0.5
    front_overhang: 0.43
    rear_overhang: 0.08
    wheel_base: 0.324
    steering_speed: 3.2
    scan_down_sample_scale: 2.0
    range_thresh_min: 2.0
    range_thresh_max: 8.0
    min_gap_size: 0.8
    goal_angle: 0.0
    wall_clearance_min: 0.20
    wall_clearance_max: 0.57
    min_speed: 1.0
    max_speed: 5.2
    boost_speed: 18.0
    boost_dist_thresh: 4.8
    acceleration: 4.5
    small_angle_kp: 0.35
    large_angle_kp: 0.51