version: '3.8'

name: autodrive_devkit_roboracer_api
services:
  roboracer_api:
    image: autodriveecosystem/autodrive_roboracer_api:2025-icra-practice
    pull_policy: always
    runtime: nvidia
    network_mode: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../my_project:/home/autodrive_devkit/src/my_project:rw
