services:
  roboracer_api:
    container_name: autodrive_roboracer_api
    image: autodriveecosystem/autodrive_roboracer_api:2025-icra-practice
    pull_policy: always
    runtime: nvidia
    network_mode: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../autoware:/home/autodrive_devkit/src/autoware:rw
